services:
  web:
    build: .
    container_name: testapp-web-1
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./app/static/uploads:/app/static/uploads
    environment:
      FLASK_APP: "app"
      FLASK_ENV: "development"
    command: python -m flask run --host=0.0.0.0
